### ISSUE TITLE
CORS header allow access control origin missing

### ISSUE THREAD

**Issue by ghost** [w3slley/bookcover-api#10]
I am trying to make an AJAX GET request to your app using jQuery from the Browser, but I get the error "CORS header allow access control origin missing." 

I tried setting dataType to jsonp but that gives me a syntax error, unexpected ":"
```
$.ajax({
		   url: "https://bookcoverapi.herokuapp.com/bookcover?book_title="+uploadModel.title + "&author_name=" + uploadModel.author,
		   headers: {  'Access-Control-Allow-Origin': '*' },
		   crossDomain:true,
		   type: 'GET',
		   success: function(data){
		   	console.log(data.url);
		   },
		   error: function(error){
		   	console.log(error);
		   }
		}) 
```

**Comment by rachelspencer** [comment]
@w3slley Hi, I am also running into this issue. Is there any way you could add this header to the response from your API? I would really appreciate any help. I'm excited to utilize your api because it solves the exact problem I've had in my project (no high-res book covers). Thanks!

**Comment by w3slley** [comment]
Hey @DubiousTunic  and @rachelspencer. The PR #16 added the `'Access-Control-Allow-Origin': *` header, so you should already be able to make an HTTP request from your app.

**Comment by ChiefWoods** [comment]
```
async function getBookCover(title, author) {
  const url = new URL("https://api.bookcover.longitood.com/bookcover");

  url.searchParams.append("book_title", title);
  url.searchParams.append("author_name", author);

  return await fetch(url, {})
    .then((response) => response.json())
    .then((data) => data.url)
    .catch(err => console.error(err));
}
```

Still getting the same error
