### ISSUE TITLE
Issue when calling api

### ISSUE THREAD

**Issue by khushwin0303** [w3slley/bookcover-api#2]
<!DOCTYPE html>
<html>

<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="utf-8">
	<title>Application Error</title>
	<style media="screen">
		html,
		body,
		iframe {
			margin: 0;
			padding: 0;
		}

		html,
		body {
			height: 100%;
			overflow: hidden;
		}

		iframe {
			width: 100%;
			height: 100%;
			border: 0;
		}
	</style>
</head>

<body>
	<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
</body>

</html>

**Comment by w3slley** [comment]
Fixed!
