### ISSUE TITLE
Search by ISBN

### ISSUE THREAD

**Issue by kstawinski** [w3slley/bookcover-api#4]
Hi, have you though about add searching covers using ISBN number? In my opinion it will be more precise and excude possible troubles with non matching cover.

By the way, thank you so much for this project. As you wrote, there is no good book cover finder app, so now I can do more with my "reading app" and reduce a lot of unnecessary code ;)

**Comment by w3slley** [comment]
Hey @kstawinski, thanks for the suggestion! Yeah, that's probably a good idea since there could be some mismatch for some books - searches with only the `bookTitle` parameter could lead to incorrect results when there is more than one book with that same title.

**Comment by w3slley** [comment]
PR https://github.com/w3slley/bookcover-api/pull/7 added the possibility to search by ISBN!
