### ISSUE TITLE
Getting "Request failed with status code 429" error

### ISSUE THREAD

**Issue by tonydavidx** [w3slley/bookcover-api#8]
recently i am getting this 429 error. is there any rate limits now?

**Comment by flame05** [comment]
UPDATE:
forked the code, made a free heroku account, connected my github and manually deployed the master branch. Working like a charm. Cheers

**Comment by w3slley** [comment]
Hey! There aren't limits at the application level for now but there are still limits at the infrastructure level. If the project gets too much traction it'll make sense to add more processing power to the containers running on Heroku.
