### ISSUE TITLE
Why not just return the book cover image url or at least have that as an option

### ISSUE THREAD

**Issue by danecjensen** [w3slley/bookcover-api#9]

**Comment by w3slley** [comment]
Hey @danecjensen. Actually there are no other fields being returned other than the status of the request and the url itself. Could you please clarify?

**Comment by danecjensen** [comment]
Return an http content type image/jpeg

**Comment by w3slley** [comment]
This project only outputs links of images hosted on other places on the internet, so it makes sense to return their link and not the image itself.
